import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "../../components/NavBar";
import { AppProvider } from "../../context/Context";
import ToggleTheme from "../../components/ToggleTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <header className="bg-red-600">
            <NavBar />
          </header>
          <ToggleTheme />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
